const PHOTO={
LADA:'https://kolesa-uploads.ru/-/21f53b32-e6a9-425b-985b-96f774ed1195/lada-vesta-red-054.jpg',
BMW:'https://myskillsconnect.com/uploads/posts/2023-06/1687622405_myskillsconnect-com-p-luchshie-foto-bmv-ye60-11.jpg',
Kia:'https://avatars.mds.yandex.net/get-autoru-vos/2153068/1ab6de5b125fd6c55c1ae8e9e3bab6a9/1200x900',
Hyundai:'https://www.planetcarsz.com/assets/uploads/2017/02/HYUNDAI%20SOLARIS%202017%2006.jpg',
Volkswagen:'https://avatars.mds.yandex.net/get-autoru-vos/2164685/50846da477703fac78117e81b83399f2/1200x900',
Toyota:'https://avatars.mds.yandex.net/get-autoru-vos/2087465/c85f3fbc4be0a166240659ca586024f4/1200x900',
'Mercedes-Benz':'https://a1.drive-data.ru/Vfy3aJAE0n_EpN3O4AGZtga3ufA-960.jpg',
Audi:'https://avatars.mds.yandex.net/get-autoru-vos/6027420/8be9754d0e5b25a527394f529e5bfef7/1200x900',
Ford:'https://images.unsplash.com/photo-1502877338535-766e1452684a',
Skoda:'https://hdpic.club/uploads/posts/2021-12/1639325719_23-hdpic-club-p-shkoda-rapid-23.jpg',
Renault:'https://journal.carso.ru/wp-content/uploads/2025/10/renault-logan.jpg',
Nissan:'https://cdn5.vedomosti.ru/image/2021/76/zbisc/original-19ry.jpg',
Mazda:'https://avatars.mds.yandex.net/get-autoru-vos/16743792/e8c52951c0edefc9541edf89b1ec96e7/1200x900',
Honda:'https://www.ixbt.com/img/nw/news/2024/2/1/Honda%20CR-V_large.jpg',
Mitsubishi:'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'
};
const modelGroups={
LADA:['ВАЗ-2101','ВАЗ-2103','ВАЗ-2106','ВАЗ-2107','ВАЗ-2114','ВАЗ-2115','Priora','Granta','Vesta','Niva Legend'],
BMW:['E39 520i','E60 520i','E60 525d','E60 530i','F10 520d','F10 528i','F30 320i','F30 328i','X5 E70','X3 F25'],
Kia:['Rio','Ceed','Cerato','Optima','Sportage','Sorento','Soul','Seltos','K5','Mohave'],
Hyundai:['Solaris','Elantra','i30','Sonata','Creta','Tucson','Santa Fe','ix35','Kona','Accent'],
Volkswagen:['Polo','Jetta','Golf','Passat B7','Passat B8','Tiguan','Touareg','Transporter T5','Transporter T6','Arteon'],
Toyota:['Corolla','Camry','RAV4','Land Cruiser 100','Land Cruiser 200','Avensis','C-HR','Highlander','Prius','Mark II'],
'Mercedes-Benz':['C-Class W204','E-Class W212','E-Class W213','S-Class W221','GLK X204','GLE W166','GLC X253','Vito W639','Sprinter W906','A-Class W176'],
Audi:['A3 8V','A4 B8','A4 B9','A6 C6','A6 C7','Q3 8U','Q5 8R','Q7 4L','TT 8J','A8 D4'],
Ford:['Focus II','Focus III','Focus IV','Mondeo IV','Mondeo V','Kuga II','Explorer V','Fiesta','Transit','EcoSport'],
Skoda:['Rapid','Octavia A5','Octavia A7','Octavia A8','Superb II','Superb III','Yeti','Kodiaq','Karoq','Fabia'],
Renault:['Logan I','Logan II','Sandero','Sandero Stepway','Duster','Kaptur','Arkana','Fluence','Megane III','Koleos'],
Nissan:['Almera','Qashqai J10','Qashqai J11','X-Trail T31','X-Trail T32','Terrano','Murano Z51','Teana J32','Note','Tiida'],
Mazda:['Mazda 3 BK','Mazda 3 BL','Mazda 3 BM','Mazda 6 GH','Mazda 6 GJ','CX-5','CX-7','CX-9','CX-30','CX-60'],
Honda:['Civic VIII','Civic IX','Accord VIII','Accord IX','CR-V III','CR-V IV','CR-V V','Pilot II','Pilot III','HR-V'],
Mitsubishi:['Lancer IX','Lancer X','Outlander II','Outlander III','Pajero IV','ASX','Eclipse Cross','Pajero Sport II','Pajero Sport III','Galant IX']
};
const cities=['Москва','Санкт-Петербург','Казань','Нижний Новгород','Екатеринбург','Краснодар','Ростов-на-Дону','Самара','Уфа','Челябинск'];
const cityMult={Москва:1.06,'Санкт-Петербург':1.04,Казань:0.98,'Нижний Новгород':0.96,Екатеринбург:0.94,Краснодар:1.01,'Ростов-на-Дону':0.97,Самара:0.95,Уфа:0.93,Челябинск:0.92};
const descTemplates=[
'Автомобиль использовался преимущественно в городе. Владелец описывает его спокойно, без громких обещаний. Есть обычные следы эксплуатации.',
'Машина обслуживалась по мере необходимости. Салон сохранён, по кузову есть несколько косметических моментов. Осмотр приветствуется.',
'Продаётся в состоянии, соответствующем возрасту и пробегу. По словам владельца, основные функции работают штатно.',
'Автомобиль выглядит аккуратно. Есть небольшие потёртости и сколы, которые лучше увидеть при личном осмотре. Документы готовы.',
'Владелец не торопится, но готов обсудить цену возле машины. По технике серьёзных жалоб не заявляет.'
];
const reasons=['Купил другую машину','Нужны деньги','Машина стала второй в семье','Переезд','Хочу автомобиль поновее','Езжу мало, решил продать'];
const sellers=['Алексей','Дмитрий','Сергей','Максим','Илья','Андрей','Никита','Роман','Влад','Евгений'];
const colors=['Белый','Чёрный','Серый','Серебристый','Синий','Красный','Коричневый'];
let id=1;const cars=[];
Object.entries(modelGroups).forEach(([brand,models])=>models.forEach((model,mi)=>{
 const year=Math.max(2004,2010+((mi*3+brand.length)%13));
 const base={LADA:180000,BMW:650000,Kia:650000,Hyundai:620000,Volkswagen:650000,Toyota:720000,'Mercedes-Benz':800000,Audi:700000,Ford:430000,Skoda:500000,Renault:380000,Nissan:520000,Mazda:520000,Honda:550000,Mitsubishi:500000}[brand];
 const price=Math.round((base+mi*85000+((id*731)%170000))*cityMult[cities[id%cities.length]]/1000)*1000;
 const mileage=Math.round((45000+((id*17321)%190000))/1000)*1000;
 const state=mileage>170000?'Нормальное':mileage>115000?'Хорошее':'Отличное';
 const engine=(mi%3===0?'1.6 л · бензин · МКПП':mi%3===1?'2.0 л · бензин · АКПП':'1.8 л · бензин · АКПП');
 cars.push({id:id++,brand,model,year,mileage,state,price,engine,color:colors[(id+mi)%colors.length],city:cities[(id+mi)%cities.length],owners:1+(id%4),registered:year+1+(id%3),reason:reasons[id%reasons.length],urgent:id%5===0,views:18+(id*37)%160,favs:id%9,listedDays:1+(id%14),seller:sellers[id%sellers.length],sellerStyle:['спокойный','торгующийся','занятый','дружелюбный','настороженный'][id%5],photo:PHOTO[brand],desc:descTemplates[id%descTemplates.length]});
}));
const brands=['Все',...Object.keys(modelGroups)];
const filters={brand:'Все',city:'Все',minPrice:'',maxPrice:'',minYear:'',maxMileage:'',sort:'new'};
let balance=Number(localStorage.getItem('p_balance')||1500000), garage=JSON.parse(localStorage.getItem('p_garage')||'[]'), bought=new Set(JSON.parse(localStorage.getItem('p_bought')||'[]')), favorites=JSON.parse(localStorage.getItem('p_favs')||'{}'), listings=JSON.parse(localStorage.getItem('p_listings')||'[]');
let gameHour=Number(localStorage.getItem('p_hour')||10), sleepLeft=Number(localStorage.getItem('p_sleep')||12), day=Number(localStorage.getItem('p_day')||1), profit=Number(localStorage.getItem('p_profit')||0);
const $=s=>document.querySelector(s), money=n=>Math.round(n).toLocaleString('ru-RU');
function save(){localStorage.setItem('p_balance',balance);localStorage.setItem('p_garage',JSON.stringify(garage));localStorage.setItem('p_bought',JSON.stringify([...bought]));localStorage.setItem('p_favs',JSON.stringify(favorites));localStorage.setItem('p_listings',JSON.stringify(listings));localStorage.setItem('p_hour',gameHour);localStorage.setItem('p_sleep',sleepLeft);localStorage.setItem('p_day',day);localStorage.setItem('p_profit',profit);updateTop();}
function updateTop(){ $('#balance').textContent=money(balance);$('#garageCount').textContent=garage.length;$('#time').textContent=`День ${day} · ${String(gameHour).padStart(2,'0')}:00`; }
function imgVariants(url){return [url,url,url,url,url]}
function galleryHTML(c){const imgs=imgVariants(c.photo);return `<div class="gallery"><img class="mainPhoto" src="${imgs[0]}" alt="${c.brand} ${c.model}"><div class="thumbs">${imgs.map((u,i)=>`<button class="thumb ${i===0?'sel':''}" onclick="swapPhoto(this,'${u}')"><img src="${u}"></button>`).join('')}</div></div>`}
function renderBrands(){ $('#brands').innerHTML=brands.map(b=>`<button class="brand ${filters.brand===b?'active':''}" onclick="setBrand('${b}')">${b}</button>`).join(''); }
function setBrand(b){filters.brand=b;render();renderBrands()}
function filtered(){let list=cars.filter(c=>!bought.has(c.id));if(filters.brand!=='Все')list=list.filter(c=>c.brand===filters.brand);if(filters.city!=='Все')list=list.filter(c=>c.city===filters.city);if(filters.minPrice)list=list.filter(c=>c.price>=+filters.minPrice);if(filters.maxPrice)list=list.filter(c=>c.price<=+filters.maxPrice);if(filters.minYear)list=list.filter(c=>c.year>=+filters.minYear);if(filters.maxMileage)list=list.filter(c=>c.mileage<=+filters.maxMileage);if(filters.sort==='priceAsc')list.sort((a,b)=>a.price-b.price);if(filters.sort==='priceDesc')list.sort((a,b)=>b.price-a.price);if(filters.sort==='mileage')list.sort((a,b)=>a.mileage-b.mileage);if(filters.sort==='new')list.sort((a,b)=>b.listedDays-a.listedDays);return list}
function render(){ $('#reset').style.display='block';renderBrands();let list=filtered();$('#title').textContent=filters.brand==='Все'?'Все автомобили':filters.brand;$('#count').textContent=`${list.length} объявлений`;$('#catalog').innerHTML=list.map(card).join('')||'<div class="empty">По этим параметрам машин не найдено.</div>';updateTop();}
function card(c){const fav=!!favorites[c.id];return `<article class="card"><div class="photo"><img src="${c.photo}" alt="${c.brand} ${c.model}"><span class="badge">${c.state}</span><button class="favorite ${fav?'on':''}" onclick="toggleFav(event,${c.id})">${fav?'♥':'♡'}</button></div><div class="body"><div class="name">${c.brand} ${c.model}</div><div class="sub">${c.year} · ${money(c.mileage)} км · ${c.city}</div><div class="chips"><span class="chip">${c.color}</span><span class="chip">${c.owners} владельца</span><span class="chip">${c.listedDays} дн. назад</span></div><div class="price">${money(c.price)} ₽</div><button class="buy" onclick="openCar(${c.id})">Подробнее</button></div></article>`}
function openFilters(){ $('#filtersModal').classList.remove('hidden');$('#filtersModal').innerHTML=`<div class="sheet"><h2>Фильтры</h2><div class="formGrid"><label>Город<select id="fCity"><option>Все</option>${cities.map(x=>`<option ${filters.city===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Цена от<input id="fMin" type="number" value="${filters.minPrice}"></label><label>Цена до<input id="fMax" type="number" value="${filters.maxPrice}"></label><label>Год от<input id="fYear" type="number" value="${filters.minYear}"></label><label>Пробег до<input id="fMileage" type="number" value="${filters.maxMileage}"></label><label>Сортировка<select id="fSort"><option value="new">По свежести</option><option value="priceAsc">Сначала дешевле</option><option value="priceDesc">Сначала дороже</option><option value="mileage">Меньше пробег</option></select></label></div><button class="buy" onclick="applyFilters()">Применить</button><button class="buy close" onclick="$('#filtersModal').classList.add('hidden')">Закрыть</button></div>`;$('#fSort').value=filters.sort;}
function applyFilters(){filters.city=$('#fCity').value;filters.minPrice=$('#fMin').value;filters.maxPrice=$('#fMax').value;filters.minYear=$('#fYear').value;filters.maxMileage=$('#fMileage').value;filters.sort=$('#fSort').value;$('#filtersModal').classList.add('hidden');render()}
function toggleFav(e,id){e.stopPropagation();favorites[id]=!favorites[id];if(!favorites[id])delete favorites[id];save();render()}
function swapPhoto(btn,url){const m=btn.closest('.gallery').querySelector('.mainPhoto');m.src=url;btn.parentElement.querySelectorAll('.thumb').forEach(x=>x.classList.remove('sel'));btn.classList.add('sel')}
function sellerReply(c,text){const t=text.toLowerCase();if(t.includes('дорог')||t.includes('цена'))return c.sellerStyle==='торгующийся'?`Могу немного уступить, если заберёте без долгих раздумий.`:`Цена выставлена с учётом состояния и пробега. Большого торга не планирую.`;if(t.includes('дтп')||t.includes('бит')||t.includes('краск'))return c.id%3===0?`Красилось левое переднее крыло, делал предыдущий владелец. Остальное надо смотреть на месте.`:`По серьёзным ДТП ничего не знаю. Мелкая косметика есть.`;if(t.includes('мотор')||t.includes('двиг'))return `На холодную заводится нормально. Масло менялось по регламенту со слов владельца.`;if(t.includes('короб')||t.includes('акпп'))return `Переключения без явных ударов. Но диагностику перед покупкой никто не отменял.`;if(t.includes('пробег'))return c.id%4===0?`По приборке сейчас ${money(c.mileage)} км, документы лучше сверить.`:`Пробег по приборке ${money(c.mileage)} км.`;if(t.includes('скид')||t.includes('уступ'))return `Если осмотр и расчёт сегодня, могу обсудить небольшую скидку.`;return ['Да, машина ещё продаётся.','Могу показать вечером, заранее напишите.','Всё основное постарался указать в объявлении.','Лучше приезжайте и спокойно посмотрите автомобиль.'][c.id%4]}
function openCar(id){const c=cars.find(x=>x.id===id);$('#modal').classList.remove('hidden');$('#modal').innerHTML=`<div class="sheet">${galleryHTML(c)}<h2>${c.brand} ${c.model}</h2><div class="priceBig">${money(c.price)} ₽</div><div class="meta"><div><small>Год</small><b>${c.year}</b></div><div><small>Пробег</small><b>${money(c.mileage)} км</b></div><div><small>Город</small><b>${c.city}</b></div><div><small>Владельцы</small><b>${c.owners}</b></div><div><small>Постановка на учёт</small><b>${c.registered}</b></div><div><small>Цвет</small><b>${c.color}</b></div></div><div class="chips"><span class="chip">Объявление ${c.listedDays} дн.</span><span class="chip">${c.views} просмотров</span><span class="chip">${c.favs} в избранном</span>${c.urgent?'<span class="chip warn">Срочная продажа</span>':''}</div><div class="box"><small>ОПИСАНИЕ</small>${c.desc}</div><div class="box"><small>ПРИЧИНА ПРОДАЖИ</small>${c.reason}</div><div class="chat" id="chat"><b>${c.seller}</b>: «${sellerReply(c,'привет')}»</div><div class="chatInput"><input id="msg" placeholder="Написать продавцу..."><button class="smallBtn" onclick="sendMsg(${id})">Отправить</button></div><div class="actions"><button class="buy secondary" onclick="haggling(${id})">Торг</button><button class="buy" onclick="buy(${id},${c.price})">Купить</button></div><button class="buy secondary" onclick="buyReport(${id})">Автотека · 150 ₽</button><button class="buy secondary" onclick="vinCheck(${id})">VIN-проверка · 250 ₽</button><button class="buy close" onclick="closeModal()">Закрыть</button></div>`}
function sendMsg(id){const c=cars.find(x=>x.id===id),input=$('#msg');if(!input.value.trim())return;const text=input.value.trim();$('#chat').innerHTML+=`<div class="msgMe">Вы: «${text}»</div><div class="msgSeller"><b>${c.seller}</b>: «${sellerReply(c,text)}»</div>`;input.value='';}
function haggling(id){const c=cars.find(x=>x.id===id),offer=Math.round(c.price*(0.91+(c.urgent?0.01:0)+Math.random()*.05)/1000)*1000;$('#chat').innerHTML+=`<div class="msgSeller"><b>${c.seller}</b>: «Если без долгих разговоров, могу отдать за <b>${money(offer)} ₽</b>.»</div>`;$('.actions').innerHTML=`<button class="buy" onclick="buy(${id},${offer})">Забрать за ${money(offer)} ₽</button><button class="buy secondary" onclick="openCar(${id})">Продолжить</button>`}
function buy(id,p){const c=cars.find(x=>x.id===id);if(!c||bought.has(id)){alert('Этот экземпляр уже недоступен.');return}if(balance<p){alert('Не хватает денег.');return}balance-=p;bought.add(id);garage.push({...c,buyPrice:p,diagnosed:false,ready:false,listed:false,serviceIssues:[],historyChecked:false,vinChecked:false});save();closeModal();render();}
function autodata(c){return {accidents:c.id%4===0?2:c.id%3===0?1:0,damage:c.id%4===0?'Левое крыло и передний бампер':c.id%3===0?'Задний бампер':'ДТП по официальным данным не обнаружены',realMileage:c.id%5===0?c.mileage+38000:c.mileage,twist:c.id%5===0,owners:c.owners,service:c.id%2?'Есть отдельные записи':'История обслуживания частичная'} }
function buyReport(id){const c=cars.find(x=>x.id===id);if(balance<150){alert('Не хватает денег.');return}balance-=150;const r=autodata(c);save();$('.sheet').insertAdjacentHTML('beforeend',`<div class="report"><b>Автотека</b><p>ДТП: ${r.accidents?`обнаружено — ${r.damage}`:'не обнаружено'}</p><p>Реальный пробег: ${money(r.realMileage)} км ${r.twist?'— есть расхождение с объявлением':''}</p><p>Владельцев: ${r.owners}</p><p>Обслуживание: ${r.service}</p></div>`)}
function vinCheck(id){const c=cars.find(x=>x.id===id);if(balance<250){alert('Не хватает денег.');return}balance-=250;save();$('.sheet').insertAdjacentHTML('beforeend',`<div class="report"><b>VIN-проверка</b><p>Идентификатор: ${String(c.brand).slice(0,2).toUpperCase()}-${c.id.toString().padStart(8,'0')}-RU</p><p>Юридических ограничений: ${c.id%7===0?'обнаружены — требуется осторожность':'не обнаружено'}</p><p>Регистрация: ${c.city}</p></div>`)}
function diagnose(i){const c=garage[i];if(balance<2000){alert('Не хватает денег на СТО.');return}balance-=2000;c.diagnosed=true;c.serviceIssues=makeIssues(c);save();garageView()}
function makeIssues(c){const common=[['Замена масла и фильтра',3200],['Передние тормозные колодки имеют заметный износ',4800],['Втулки стабилизатора требуют внимания',4200],['Масло в АКПП желательно обновить',7800],['Небольшая течь прокладки двигателя',6500],['Химчистка салона рекомендуется',6500]];let n=c.mileage>150000?3:c.mileage>100000?2:1;let arr=[];for(let k=0;k<n;k++){let q=common[(c.id+k*2)%common.length];arr.push({name:q[0],cost:q[1]+((c.id+k)%5)*500,done:false})}return arr}
function fixIssue(i,j){const c=garage[i],x=c.serviceIssues[j];if(x.done)return;if(balance<x.cost){alert('Не хватает денег.');return}balance-=x.cost;x.done=true;save();garageView()}
function prepare(i){const c=garage[i];if(!c.diagnosed){alert('Сначала диагностика.');return}if(c.serviceIssues.some(x=>!x.done)){alert('Сначала реши, что ремонтировать.');return}c.ready=true;save();garageView()}
function prepChoice(i,type){const c=garage[i];const costs={polish:6000,clean:7000,wheels:8000,cheapWheels:2500};const labels={polish:'Полировка кузова',clean:'Химчистка салона',wheels:'Восстановление дисков',cheapWheels:'Покраска дисков бюджетным способом'};if(balance<costs[type]){alert('Не хватает денег.');return}balance-=costs[type];c.prep=c.prep||[];c.prep.push({type,label:labels[type],quality:type==='cheapWheels'?'бюджетная':'хорошая'});save();garageView()}
function listCar(i){const c=garage[i];if(!c.ready){alert('Сначала подготовь автомобиль.');return}c.listed=true;c.listPrice=Math.round(c.buyPrice*1.18/1000)*1000;c.listCity=c.city;c.listViews=0;c.listFavs=0;c.listedAt=Date.now();save();garageView()}
function ownListing(c,i){if(!c.listed)return '';return `<div class="listingState">Выставлена: ${money(c.listPrice)} ₽ · ${c.listViews} просмотров · ${c.listFavs} в избранном · ${c.listCity}</div>`}
function garageView(){renderBrands();$('#reset').style.display='none';$('#title').textContent='Мой гараж';$('#count').textContent=`${garage.length} автомобилей`;if(!garage.length){$('#catalog').innerHTML='<div class="empty">Гараж пуст.</div>';return}$('#catalog').innerHTML=garage.map((c,i)=>`<article class="card"><div class="photo"><img src="${c.photo}"><span class="badge">${c.listed?'Выставлена':c.diagnosed?(c.serviceIssues.some(x=>!x.done)?'Есть замечания':'Проверено'):'Не проверено'}</span></div><div class="body"><div class="name">${c.brand} ${c.model}</div><div class="sub">Покупка: ${money(c.buyPrice)} ₽ · ${c.year} · ${money(c.mileage)} км</div>${c.diagnosed?`<div class="serviceBox"><div class="serviceTitle">СТО</div>${c.serviceIssues.map((x,j)=>`<div class="issue"><div><b>${x.name}</b></div><strong>${money(x.cost)} ₽</strong>${x.done?'<span class="done">Готово</span>':`<button class="smallBtn" onclick="fixIssue(${i},${j})">Устранить</button>`}</div>`).join('')||'<div class="profit">Серьёзных проблем не найдено.</div>'}</div>`:''}<div class="actions"><button class="smallBtn" onclick="diagnose(${i})">${c.diagnosed?'Повторная диагностика':'СТО · 2 000 ₽'}</button>${c.diagnosed&&!c.serviceIssues.some(x=>!x.done)?`<button class="smallBtn" onclick="prepare(${i})">Подготовить</button>`:''}</div><div class="prepButtons"><button class="smallBtn" onclick="prepChoice(${i},'polish')">Полировка</button><button class="smallBtn" onclick="prepChoice(${i},'clean')">Химчистка</button><button class="smallBtn" onclick="prepChoice(${i},'wheels')">Диски</button><button class="smallBtn" onclick="prepChoice(${i},'cheapWheels')">Покрасить диски</button></div>${c.ready&&!c.listed?`<button class="buy" onclick="listCar(${i})">Выставить на продажу</button>`:''}${ownListing(c,i)}</div></article>`).join('');updateTop()}
function favoritesView(){ $('#title').textContent='Избранное';$('#count').textContent='';$('#brands').innerHTML='';$('#reset').style.display='none';const ids=Object.keys(favorites).map(Number);const items=ids.map(id=>cars.find(c=>c.id===id)).filter(Boolean);$('#catalog').innerHTML=items.map(c=>bought.has(c.id)?`<article class="card sold"><div class="body"><div class="name">${c.brand} ${c.model}</div><div class="sub">Объявление снято с продажи</div></div></article>`:card(c)).join('')||'<div class="empty">В избранном пока ничего нет.</div>'}
function timeView(){ $('#modal').classList.remove('hidden');$('#modal').innerHTML=`<div class="sheet"><h2>Время</h2><p>Сегодня: день ${day}, ${String(gameHour).padStart(2,'0')}:00</p><p>Доступно сна сегодня: ${sleepLeft} ч.</p><div class="timeBtns">${[1,3,6,12].map(h=>`<button class="buy ${h>sleepLeft?'disabled':''}" onclick="sleep(${h})">Поспать ${h} ч.</button>`).join('')}</div><button class="buy close" onclick="closeModal()">Закрыть</button></div>`}
function sleep(h){if(h>sleepLeft){alert('На сегодня лимит сна исчерпан.');return}sleepLeft-=h;gameHour+=h;while(gameHour>=24){gameHour-=24;day++;sleepLeft=12;}cars.forEach(c=>{if(Math.random()<.08)c.price=Math.round(c.price*(.97+Math.random()*.05)/1000)*1000;if(Math.random()<.05)c.listedDays+=1});listings.forEach(x=>{if(x.active&&Math.random()<.12)x.listViews+=1;if(x.active&&Math.random()<.06)x.listFavs+=1});save();closeModal();render()}
function showMarket(){ $('#marketTab').classList.add('active');$('#garageTab').classList.remove('active');$('#favTab').classList.remove('active');render()}
function showGarage(){ $('#marketTab').classList.remove('active');$('#garageTab').classList.add('active');$('#favTab').classList.remove('active');garageView()}
function showFav(){ $('#marketTab').classList.remove('active');$('#garageTab').classList.remove('active');$('#favTab').classList.add('active');favoritesView()}
function closeModal(){ $('#modal').classList.add('hidden') }
$('#marketTab').onclick=showMarket;$('#garageTab').onclick=showGarage;$('#favTab').onclick=showFav;$('#filterBtn').onclick=openFilters;$('#timeBtn').onclick=timeView;$('#reset').onclick=()=>{Object.assign(filters,{brand:'Все',city:'Все',minPrice:'',maxPrice:'',minYear:'',maxMileage:'',sort:'new'});render()};updateTop();render();
