const cars=[
{id:1,brand:"LADA",model:"2106",year:2001,mileage:168000,state:"Нормальное",price:85000,repair:18000,seller:"Сергей"},
{id:2,brand:"LADA",model:"Priora",year:2011,mileage:142000,state:"Хорошее",price:245000,repair:12000,seller:"Алексей"},
{id:3,brand:"Kia",model:"Rio",year:2015,mileage:119000,state:"Хорошее",price:690000,repair:25000,seller:"Максим"},
{id:4,brand:"Hyundai",model:"Solaris",year:2017,mileage:93000,state:"Отличное",price:890000,repair:8000,seller:"Дмитрий"},
{id:5,brand:"BMW",model:"3 Series",year:2013,mileage:154000,state:"Среднее",price:1180000,repair:90000,seller:"Илья"},
{id:6,brand:"Volkswagen",model:"Polo",year:2018,mileage:78000,state:"Хорошее",price:970000,repair:18000,seller:"Антон"}
];
let balance=150000, garage=JSON.parse(localStorage.getItem("garage")||"[]");
const $=id=>document.getElementById(id);
function money(n){return n.toLocaleString("ru-RU")}
function save(){localStorage.setItem("garage",JSON.stringify(garage));$("balance").textContent=money(balance);$("garageCount").textContent=garage.length}
function market(){ $("market").innerHTML='<div class="grid">'+cars.map(c=>`<article class="card"><div class="carpic">🚗</div><div class="info"><div class="title">${c.brand} ${c.model}</div><div class="muted">${c.year} год · ${money(c.mileage)} км · ${c.state}</div><div class="tags"><span class="tag">Продавец: ${c.seller}</span><span class="tag">ремонт ≈ ${money(c.repair)} ₽</span></div><div class="price">${money(c.price)} ₽</div><button class="btn" onclick="buy(${c.id})">Открыть объявление</button></div></article>`).join("")+'</div>'}
function buy(id){let c=cars.find(x=>x.id===id);$("modal").classList.remove("hidden");$("modal").innerHTML=`<div class="sheet"><h2>${c.brand} ${c.model}</h2><p>${c.year} год, пробег ${money(c.mileage)} км. Состояние: ${c.state}. Продавец: ${c.seller}.</p><p>Продавец хочет <b>${money(c.price)} ₽</b>. Можно попробовать поторговаться.</p><div class="actions"><button class="btn secondary" onclick="haggle(${id})">Поторговаться</button><button class="btn" onclick="confirmBuy(${id})">Купить</button></div><br><button class="btn secondary" onclick="closeModal()">Закрыть</button></div>`}
function haggle(id){let c=cars.find(x=>x.id===id);c.offer=Math.round(c.price*(.93+Math.random()*.03));$("modal").querySelector("p:nth-of-type(2)").innerHTML=`Продавец отвечает: «Могу отдать за <b>${money(c.offer)} ₽</b>. Дешевле не буду».`;$("modal").querySelector(".actions").innerHTML=`<button class="btn" onclick="confirmBuy(${id},${c.offer})">Забрать за ${money(c.offer)} ₽</button>`}
function confirmBuy(id,price){let c=cars.find(x=>x.id===id),p=price||c.price;if(balance<p){alert("Не хватает денег.");return}balance-=p;garage.push({...c,buy:p,ready:false});save();closeModal();garageView()}
function closeModal(){$("modal").classList.add("hidden")}
function garageView(){ $("garage").innerHTML=garage.length?'<div class="grid">'+garage.map((c,i)=>`<article class="card"><div class="carpic">🚘</div><div class="info"><div class="title">${c.brand} ${c.model}</div><div class="muted">${c.year} · ${money(c.mileage)} км</div><div class="tags"><span class="tag">Куплена за ${money(c.buy)} ₽</span>${c.ready?'<span class="tag">Подготовлена</span>':'<span class="tag danger">Нужна подготовка</span>'}</div>${!c.ready?`<button class="btn" onclick="prepare(${i})">Подготовить · ${money(c.repair)} ₽</button>`:`<button class="btn" onclick="sell(${i})">Выставить и продать</button>`}</div></article>`).join("")+'</div>':'<div class="empty">Гараж пуст. Купи первый автомобиль на рынке.</div>'}
function prepare(i){let c=garage[i];if(balance<c.repair){alert("Не хватает денег на подготовку.");return}balance-=c.repair;c.ready=true;save();garageView()}
function sell(i){let c=garage[i],base=c.buy+c.repair;let sale=Math.round(base*(1.05+Math.random()*.25));balance+=sale;garage.splice(i,1);save();alert(`Сделка завершена. Продано за ${money(sale)} ₽. Прибыль: ${money(sale-base)} ₽.`);garageView()}
function rating(){$("rating").innerHTML=`<div class="rank"><b>1. AutoKing</b><div class="muted">Заработано: 18 420 000 ₽</div></div><div class="rank"><b>2. VAZ_BOSS</b><div class="muted">Заработано: 15 870 000 ₽</div></div><div class="rank"><b>3. TurboMax</b><div class="muted">Заработано: 12 340 000 ₽</div></div><div class="rank"><b>4. Ты</b><div class="muted">Заработано: 0 ₽ · Новичок</div></div>`}
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active");if(b.dataset.tab==="garage")garageView();if(b.dataset.tab==="rating")rating()});
market();save();
