const PHOTO={
LADA:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lada%20Vesta.jpg',BMW:'https://commons.wikimedia.org/wiki/Special:Redirect/file/BMW%20530i%20E60%20sedan.jpg',Kia:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kia%20Ceed%20SW%202019.jpg',Hyundai:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Hyundai%20Solaris%20II.jpg',Volkswagen:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Volkswagen%20Polo%20VI.jpg',Toyota:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota%20Camry%20XV70.jpg','Mercedes-Benz':'https://commons.wikimedia.org/wiki/Special:Redirect/file/00%20Mercedes-Benz%20W212.jpg',Audi:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Audi%20A4%20B9.jpg',Ford:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ford%20Focus%20III.jpg',Skoda:'https://commons.wikimedia.org/wiki/Special:Redirect/file/%C5%A0koda%20Rapid%20%28Russia%29.jpg',Renault:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Renault%20Logan%20II.jpg',Nissan:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nissan%20Qashqai%20J11.jpg',Mazda:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mazda%206%20GJ.jpg',Honda:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Honda%20CR-V%20IV.jpg',Mitsubishi:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mitsubishi%20Lancer%20X.jpg',Chevrolet:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chevrolet%20Niva.jpg',Opel:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Opel%20Astra%20J.jpg',Peugeot:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Peugeot%20408.jpg',Citroen:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Citroen%20C4.jpg',Subaru:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Subaru%20Forester%20SH.jpg',Volvo:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Volvo%20XC90%20II.jpg',Geely:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Geely%20Atlas.jpg',Chery:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chery%20Tiggo%207%20Pro.jpg',Haval:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Haval%20F7.jpg',Exeed:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Exeed%20TXL.jpg',GAZ:'https://commons.wikimedia.org/wiki/Special:Redirect/file/GAZ%20311%2005.jpg'};
const MODEL_PHOTO={'ВАЗ-2101':'https://commons.wikimedia.org/wiki/Special:Redirect/file/001%20Zhiguli%20-%20panoramio.jpg','ВАЗ-2103':'https://commons.wikimedia.org/wiki/Special:Redirect/file/VAZ-2103.jpg','ВАЗ-2106':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Red%20VAZ-2106%20in%20Saint%20Petersburg%2C%20Russia.jpg','ВАЗ-2107':'https://commons.wikimedia.org/wiki/Special:Redirect/file/%D0%92%D0%90%D0%97%202107.jpg','ВАЗ-2114':'https://commons.wikimedia.org/wiki/Special:Redirect/file/VAZ-2114%20Samara%20%28Saint%20Petersburg%2C%20Russia%29.jpg','ВАЗ-2115':'https://commons.wikimedia.org/wiki/Special:Redirect/file/VAZ-2115.jpg','Priora':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lada%20Priora.jpg','Granta':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lada%20Granta%20in%20Moscow%202024%20front.jpg','Vesta':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lada%20Vesta.jpg','Niva Legend':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lada%20Niva%20Legend%20BLACK%20black%20front.jpg'};
const modelGroups={
LADA:['ВАЗ-2101','ВАЗ-2103','ВАЗ-2106','ВАЗ-2107','ВАЗ-2114','ВАЗ-2115','Priora','Granta','Vesta','Niva Legend'],
BMW:['E39 520i','E39 525i','E39 530d','E46 318i','E46 320i','E46 325i','E60 520i','E60 525d','E60 530i','E60 530d'],
Kia:['Rio II','Rio III','Rio IV','Ceed I','Ceed II','Ceed III','Cerato II','Cerato III','Optima III','Optima IV'],
Hyundai:['Solaris I','Solaris II','Elantra IV','Elantra V','Elantra VI','Elantra VII','i30 II','i30 III','Sonata VI','Sonata VII'],
Volkswagen:['Polo IV','Polo V','Polo VI','Jetta V','Jetta VI','Jetta VII','Golf V','Golf VI','Golf VII','Golf VIII'],
Toyota:['Corolla E120','Corolla E150','Corolla E170','Corolla E210','Camry XV30','Camry XV40','Camry XV50','Camry XV70','Camry XV80','RAV4 III'],
'Mercedes-Benz':['C-Class W203','C-Class W204','C-Class W205','E-Class W211','E-Class W212','E-Class W213','S-Class W221','S-Class W222','GLK X204','GLE W166'],
Audi:['A3 8P','A3 8V','A3 8Y','A4 B7','A4 B8','A4 B9','A6 C5','A6 C6','A6 C7','A6 C8'],
Ford:['Focus I','Focus II','Focus III','Focus IV','Mondeo III','Mondeo IV','Mondeo V','Kuga I','Kuga II','Kuga III'],
Skoda:['Fabia I','Fabia II','Fabia III','Fabia IV','Rapid','Rapid II','Octavia A5','Octavia A7','Octavia A8','Superb I'],
Renault:['Logan I','Logan II','Logan III','Sandero I','Sandero II','Sandero Stepway I','Sandero Stepway II','Duster I','Duster II','Kaptur'],
Nissan:['Almera N16','Almera G15','Qashqai J10','Qashqai J11','Qashqai J12','X-Trail T30','X-Trail T31','X-Trail T32','Terrano III','Murano Z50'],
Mazda:['Mazda 2 DE','Mazda 3 BK','Mazda 3 BL','Mazda 3 BM','Mazda 3 BP','Mazda 6 GG','Mazda 6 GH','Mazda 6 GJ','Mazda 6 GL','CX-5 I'],
Honda:['Civic VII','Civic VIII','Civic IX','Civic X','Accord VII','Accord VIII','Accord IX','CR-V II','CR-V III','CR-V IV'],
Mitsubishi:['Lancer IX','Lancer X','Galant IX','Outlander I','Outlander II','Outlander III','Pajero III','Pajero IV','Pajero Sport I','Pajero Sport II'],
Chevrolet:['Niva','Aveo T200','Aveo T250','Cruze J300','Cruze J400','Lacetti','Captiva I','Captiva II','Orlando','Tahoe III'],
Opel:['Astra G','Astra H','Astra J','Astra K','Corsa C','Corsa D','Corsa E','Insignia A','Insignia B','Mokka A'],
Peugeot:['206','207','208','301','307','308 I','308 II','408 I','408 II','508 I'],
Citroen:['C1','C3 I','C3 II','C3 III','C4 I','C4 II','C4 III','C4 Sedan','C5 I','C5 II'],
Subaru:['Impreza GD','Impreza GH','Impreza GP','Legacy BL','Legacy BM','Forester SG','Forester SH','Forester SJ','Forester SK','Outback BP'],
Volvo:['S40 II','S60 I','S60 II','S60 III','S80 II','V40','V50','V60 I','V60 II','V70 III'],
Geely:['Emgrand EC7','Emgrand X7','Atlas I','Atlas Pro','Coolray','Tugella','Monjaro','Okavango','Geometry C','Preface'],
Chery:['Tiggo 2','Tiggo 3','Tiggo 4','Tiggo 4 Pro','Tiggo 5','Tiggo 7','Tiggo 7 Pro','Tiggo 8','Tiggo 8 Pro','Arrizo 5'],
Haval:['H2','H5','H6','H9','F7','F7x','Jolion','Dargo','Dargo X','M6'],
Exeed:['TXL','LX','VX','RX','RX II','TX','LX FL','VX FL','RX FL','Sterra ES'],
GAZ:['3110','31105','Volga Siber','Gazelle Business','Gazelle Next','Gazelle NN','Sobol','Sobol NN','Gazelle 3302','GAZelle City']
};
const cities=['Москва','Санкт-Петербург','Казань','Нижний Новгород','Екатеринбург','Краснодар','Ростов-на-Дону','Самара','Уфа','Челябинск'];
const cityMult={Москва:1.06,'Санкт-Петербург':1.04,Казань:.98,'Нижний Новгород':.96,Екатеринбург:.94,Краснодар:1.01,'Ростов-на-Дону':.97,Самара:.95,Уфа:.93,Челябинск:.92};
const basePrice={LADA:180000,BMW:650000,Kia:650000,Hyundai:620000,Volkswagen:650000,Toyota:720000,'Mercedes-Benz':800000,Audi:700000,Ford:430000,Skoda:500000,Renault:380000,Nissan:520000,Mazda:520000,Honda:550000,Mitsubishi:500000,Chevrolet:420000,Opel:430000,Peugeot:400000,Citroen:390000,Subaru:600000,Volvo:650000,Geely:650000,Chery:620000,Haval:700000,Exeed:1100000,GAZ:300000};
const descTemplates=['Автомобиль использовался преимущественно в городе. Есть обычные следы эксплуатации, владелец готов показать машину.','Машина обслуживалась по мере необходимости. Салон сохранён, по кузову есть несколько косметических моментов.','Продаётся в состоянии, соответствующем возрасту и пробегу. Основные функции работают штатно.','Автомобиль выглядит аккуратно. Есть небольшие потёртости и сколы, лучше оценить при личном осмотре.','Владелец готов обсудить цену возле машины. По технике серьёзных жалоб не заявляет.'];
const reasons=['Купил другую машину','Нужны деньги','Машина стала второй в семье','Переезд','Хочу автомобиль поновее','Езжу мало, решил продать'];
const sellers=['Алексей','Дмитрий','Сергей','Максим','Илья','Андрей','Никита','Роман','Влад','Евгений'];
const colors=['Белый','Чёрный','Серый','Серебристый','Синий','Красный','Коричневый'];
const sellerStyles=['спокойный','торгующийся','занятый','дружелюбный','настороженный'];
let id=1;const cars=[];
Object.entries(modelGroups).forEach(([brand,models])=>models.forEach((model,mi)=>{const year=Math.max(2004,2008+((mi*3+brand.length)%16));const price=Math.round((basePrice[brand]+mi*48000+((id*731)%190000))*cityMult[cities[id%cities.length]]/1000)*1000;const mileage=Math.round((35000+((id*17321)%205000))/1000)*1000;const state=mileage>175000?'Нормальное':mileage>115000?'Хорошее':'Отличное';const engine=(mi%4===0?'1.6 л · бензин · МКПП':mi%4===1?'2.0 л · бензин · АКПП':mi%4===2?'1.8 л · бензин · МКПП':'2.0 л · бензин · АКПП');cars.push({id:id++,brand,model,year,mileage,state,price,engine,color:colors[(id+mi)%colors.length],city:cities[(id+mi)%cities.length],owners:1+(id%4),registered:year+1+(id%3),reason:reasons[id%reasons.length],urgent:id%6===0,views:18+(id*37)%160,favs:id%9,listedDays:1+(id%14),seller:sellers[id%sellers.length],sellerStyle:sellerStyles[id%sellerStyles.length],photo:'',photoSet:[],desc:descTemplates[id%descTemplates.length],inspectSeed:(id*17)%100,testDriveSeed:(id*29)%100,conditionSeed:(id*43)%100});}));
const brands=['Все',...Object.keys(modelGroups)];
const filters={brand:'Все',city:'Все',minPrice:'',maxPrice:'',minYear:'',maxMileage:'',sort:'new'};
let balance=Number(localStorage.getItem('p_balance')||1500000),garage=JSON.parse(localStorage.getItem('p_garage')||'[]'),bought=new Set(JSON.parse(localStorage.getItem('p_bought')||'[]')),favorites=JSON.parse(localStorage.getItem('p_favs')||'{}'),listings=JSON.parse(localStorage.getItem('p_listings')||'[]');
let gameHour=Number(localStorage.getItem('p_hour')||10),sleepLeft=Number(localStorage.getItem('p_sleep')||12),day=Number(localStorage.getItem('p_day')||1),profit=Number(localStorage.getItem('p_profit')||0),currentCity=localStorage.getItem('p_current_city')||'Москва';let achievements=JSON.parse(localStorage.getItem('p_achievements')||'{}');
const $=s=>document.querySelector(s),money=n=>Math.round(n).toLocaleString('ru-RU');
garage=garage.map(c=>({...c,prep:c.prep||[],deal:c.deal||{buy:c.buyPrice||0,repair:0,prep:0,inspection:0,sale:0},serviceIssues:c.serviceIssues||[]}));
function save(){localStorage.setItem('p_balance',balance);localStorage.setItem('p_garage',JSON.stringify(garage));localStorage.setItem('p_bought',JSON.stringify([...bought]));localStorage.setItem('p_favs',JSON.stringify(favorites));localStorage.setItem('p_listings',JSON.stringify(listings));localStorage.setItem('p_hour',gameHour);localStorage.setItem('p_sleep',sleepLeft);localStorage.setItem('p_day',day);localStorage.setItem('p_profit',profit);localStorage.setItem('p_current_city',currentCity);localStorage.setItem('p_achievements',JSON.stringify(achievements));updateTop();}
function updateTop(){$('#balance').textContent=money(balance);$('#garageCount').textContent=garage.length;$('#time').textContent=`День ${day} · ${String(gameHour).padStart(2,'0')}:00`;}
function renderBrands(){$('#brands').innerHTML=brands.map(b=>`<button class="brand ${filters.brand===b?'active':''}" onclick="setBrand('${b}')">${b}</button>`).join('');}
function setBrand(b){filters.brand=b;render();}
function filtered(){let list=cars.filter(c=>!bought.has(c.id));if(filters.brand!=='Все')list=list.filter(c=>c.brand===filters.brand);if(filters.city!=='Все')list=list.filter(c=>c.city===filters.city);if(filters.minPrice)list=list.filter(c=>c.price>=+filters.minPrice);if(filters.maxPrice)list=list.filter(c=>c.price<=+filters.maxPrice);if(filters.minYear)list=list.filter(c=>c.year>=+filters.minYear);if(filters.maxMileage)list=list.filter(c=>c.mileage<=+filters.maxMileage);if(filters.sort==='priceAsc')list.sort((a,b)=>a.price-b.price);if(filters.sort==='priceDesc')list.sort((a,b)=>b.price-a.price);if(filters.sort==='mileage')list.sort((a,b)=>a.mileage-b.mileage);if(filters.sort==='new')list.sort((a,b)=>a.listedDays-b.listedDays);return list;}
function render(){renderBrands();let list=filtered();$('#title').textContent=filters.brand==='Все'?'Все автомобили':filters.brand;$('#count').textContent=`${list.length} объявлений`;$('#catalog').innerHTML=list.map(card).join('')||'<div class="empty">По этим параметрам машин не найдено.</div>';updateTop();}
function card(c){const fav=!!favorites[c.id];return `<article data-model="${c.model}" data-brand="${c.brand}" class="card"><div class="photo"><img data-car-photo src="${c.photo}" alt="${c.brand} ${c.model}" onerror="this.style.display='none';this.parentElement.classList.add('noPhoto')"><span class="badge">${c.state}</span><button class="favorite ${fav?'on':''}" onclick="toggleFav(${c.id})">${fav?'♥':'♡'}</button></div><div class="body"><div class="name">${c.brand} ${c.model}</div><div class="sub">${c.year} · ${money(c.mileage)} км · ${c.city}</div><div class="chips"><span class="chip">${c.color}</span><span class="chip">${c.owners} владельца</span><span class="chip">${c.listedDays} дн. назад</span><span class="chip">${c.views} просмотров</span><span class="chip">${c.favs} в избранном</span>${c.urgent?'<span class="chip warn">Срочная продажа</span>':''}</div><div class="price">${money(c.price)} ₽</div><button class="buy" onclick="openCar(${c.id})">Подробнее</button></div></article>`;}
function openFilters(){$('#filtersModal').classList.remove('hidden');$('#filtersModal').innerHTML=`<div class="sheet"><h2>Фильтры рынка</h2><div class="formGrid"><label>Город<select id="fCity">${['Все',...cities].map(x=>`<option ${filters.city===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Сортировка<select id="fSort"><option value="new" ${filters.sort==='new'?'selected':''}>Новые объявления</option><option value="priceAsc" ${filters.sort==='priceAsc'?'selected':''}>Дешевле</option><option value="priceDesc" ${filters.sort==='priceDesc'?'selected':''}>Дороже</option><option value="mileage" ${filters.sort==='mileage'?'selected':''}>Меньше пробег</option></select></label><label>Цена от<input id="fMin" type="number" value="${filters.minPrice}" placeholder="0"></label><label>Цена до<input id="fMax" type="number" value="${filters.maxPrice}" placeholder="∞"></label><label>Год от<input id="fYear" type="number" value="${filters.minYear}" placeholder="2010"></label><label>Пробег до<input id="fMileage" type="number" value="${filters.maxMileage}" placeholder="150000"></label></div><button class="buy" onclick="applyFilters()">Применить</button><button class="buy close" onclick="$('#filtersModal').classList.add('hidden')">Закрыть</button></div>`}
function applyFilters(){filters.city=$('#fCity').value;filters.sort=$('#fSort').value;filters.minPrice=$('#fMin').value;filters.maxPrice=$('#fMax').value;filters.minYear=$('#fYear').value;filters.maxMileage=$('#fMileage').value;$('#filtersModal').classList.add('hidden');render()}
function toggleFav(id){favorites[id]=!favorites[id];if(!favorites[id])delete favorites[id];save();render();}
const PHOTO_CACHE_PREFIX='p_photo_v13_exact_';
const photoInflight=new Map();
const usedPhotoUrls=new Set();
const BRAND_ALIASES={LADA:['lada','vaz','zhiguli','жигули','ваз'],BMW:['bmw'],Kia:['kia'],Hyundai:['hyundai'],Volkswagen:['volkswagen','vw','фольксваген'],Toyota:['toyota','тойота'],"Mercedes-Benz":['mercedes','mercedes benz','mercedes-benz','мерседес'],Audi:['audi','ауди'],Ford:['ford','форд'],Skoda:['skoda','škoda','шкода'],Renault:['renault','рено'],Nissan:['nissan','ниссан'],Mazda:['mazda','мазда'],Honda:['honda','хонда'],Mitsubishi:['mitsubishi','митсубиси'],Chevrolet:['chevrolet','chevy','шевроле'],Opel:['opel','опель'],Peugeot:['peugeot','пежо'],Citroen:['citroen','citroën','ситроен'],Subaru:['subaru','субару'],Volvo:['volvo','вольво'],Geely:['geely','джили'],Chery:['chery','черри'],Haval:['haval','хавал'],Exeed:['exeed','эксид'],GAZ:['gaz','газ','volga','волга','gazelle','газель']};
function normPhotoText(v){return String(v||'').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9]+/gi,' ').replace(/\s+/g,' ').trim()}
function modelTokens(model){return normPhotoText(model).split(' ').filter(x=>x.length>1)}
function photoQuerySet(brand,model){
  const b=(BRAND_ALIASES[brand]||[brand])[0];
  if(brand==='LADA'&&/^ВАЗ/.test(model)) return [`Lada ${model}`,`VAZ ${model.replace('ВАЗ-','')}`,`${model} Zhiguli`];
  if(brand==='LADA'&&model==='Niva Legend') return ['Lada Niva Legend','Lada Niva 2121','Lada 4x4 Niva'];
  if(brand==='Chevrolet'&&model==='Niva') return ['Chevrolet Niva','Chevrolet Niva VAZ-2123','Chevy Niva'];
  if(brand==='Chevrolet'&&model==='Aveo T250') return ['Chevrolet Aveo T250','Chevrolet Aveo T250 sedan'];
  if(brand==='Chevrolet'&&model==='Aveo T200') return ['Chevrolet Aveo T200','Chevrolet Aveo T200 sedan'];
  return [`${b} ${model}`,`${brand} ${model} car`,`"${brand} ${model}"`];
}
function strictPhotoScore(title,brand,model){
  const t=normPhotoText(title), aliases=(BRAND_ALIASES[brand]||[brand]).map(normPhotoText);
  const hasBrand=aliases.some(a=>a&&t.includes(a));
  if(!hasBrand)return -1000;
  const tokens=modelTokens(model);
  if(!tokens.length)return -1000;
  const base=tokens.filter(x=>!['i','ii','iii','iv','v','vi','vii','viii','ix','x','xi','xii'].includes(x));
  let score=70;
  let matched=0;
  for(const tok of base){if(t.includes(tok))matched++;}
  // Every meaningful model token must occur. This is the key fix that prevents, for example, Chevrolet Niva -> Lada Niva.
  if(matched<base.length)return -1000;
  score+=matched*12;
  const generation=tokens.filter(x=>/^e\\d+|^w\\d+|^j\\d+|^xv\\d+|^b\\d+|^a\\d+|^c\\d+|^gd$|^gh$|^gp$|^sh$|^sj$|^sk$|^bl$|^bm$|^bp$|^gg$|^gj$|^gl$|^de$|^bk$|^bm$|^1$|^2$|^3$|^4$|^5$|^6$|^7$|^8$|^9$|^10$/.test(x));
  const genHits=generation.filter(x=>t.includes(x)).length;
  if(generation.length&&genHits)score+=35;
  if(/concept|prototype|race|rally|police|truck|bus|motorcycle|motorbike/i.test(t))score-=30;
  return score;
}
async function fetchWikiPhotos(brand,model){
  const key=PHOTO_CACHE_PREFIX+encodeURIComponent(brand+'|'+model);
  if(photoInflight.has(key))return photoInflight.get(key);
  const task=(async()=>{
    try{
      const cached=JSON.parse(localStorage.getItem(key)||'null');
      if(Array.isArray(cached)&&cached.length)return cached;
      const candidates=[];
      for(const q of photoQuerySet(brand,model)){
        const u='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch='+encodeURIComponent(q)+'&gsrnamespace=6&gsrlimit=50&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=1400&format=json&origin=*';
        const r=await fetch(u); if(!r.ok)continue;
        const j=await r.json();
        for(const x of Object.values(j.query?.pages||{})){
          const info=x.imageinfo?.[0],url=info?.thumburl||info?.url;
          if(!url||usedPhotoUrls.has(url)||!/^https?:\/\//.test(url)||!/\.(jpe?g|png|webp)(\?|$)/i.test(url))continue;
          const score=strictPhotoScore(x.title,brand,model); if(score<70)continue;
          const lic=normPhotoText(info?.extmetadata?.LicenseShortName?.value||'');
          if(lic && !/(cc0|public domain|cc by|cc by sa|creative commons)/i.test(lic))continue;
          candidates.push({url,score,title:x.title,license:lic});
        }
        if(candidates.length>=15)break;
      }
      candidates.sort((a,b)=>b.score-a.score);
      const urls=[];const seen=new Set();
      for(const c of candidates){
        const sig=normPhotoText(c.title).replace(/\b\d+\b/g,'');
        if(seen.has(sig))continue;
        seen.add(sig);usedPhotoUrls.add(c.url);urls.push(c.url);
        if(urls.length>=5)break;
      }
      // Never fall back to another model or another brand. A wrong photo is worse than an empty slot.
      if(urls.length){localStorage.setItem(key,JSON.stringify(urls));return urls;}
      localStorage.setItem(key,JSON.stringify([]));return [];
    }catch(e){return []}
  })();
  photoInflight.set(key,task);return task;
}
async function loadModelPhotos(brand,model){
  const urls=await fetchWikiPhotos(brand,model);
  cars.filter(c=>c.brand===brand&&c.model===model).forEach(c=>{c.photoSet=urls;c.photo=urls[0]||''});
  document.querySelectorAll('img[data-car-photo]').forEach(img=>{const host=img.closest('[data-model]');if(host?.dataset.model===model&&host.dataset.brand===brand){img.src=urls[0]||''}});
}
function primePhotoBase(){
  const pairs=[];for(const [brand,models] of Object.entries(modelGroups))for(const model of models)pairs.push([brand,model]);
  let i=0;
  const next=()=>{const batch=pairs.slice(i,i+3);i+=3;if(!batch.length)return;Promise.all(batch.map(([brand,model])=>loadModelPhotos(brand,model))).finally(()=>setTimeout(next,300));};
  next();
}
function photoHTML(c){const set=c.photoSet&&c.photoSet.length?c.photoSet:[];return `<div class="gallery">${set.length?`<img id="detailMainPhoto" class="mainPhoto" src="${set[0]}" alt="${c.brand} ${c.model}" onerror="this.style.display='none';this.parentElement.classList.add('noPhoto')">`:`<div id="detailMainPhoto" class="mainPhoto noPhoto">Фото загружается из Wikimedia Commons</div>`}${set.length>1?`<div class="thumbs">${set.map((u,i)=>`<button class="thumb ${i===0?'sel':''}" onclick="pickDetailPhoto(${i},${c.id})"><img src="${u}" alt=""></button>`).join('')}</div>`:''}</div>`}
function pickDetailPhoto(i,id){const c=cars.find(x=>x.id===id)||garage.find(x=>x.id===id);if(!c)return;const set=c.photoSet||[c.photo];const m=$('#detailMainPhoto');if(m)m.src=set[i]||set[0];document.querySelectorAll('.thumb').forEach((x,j)=>x.classList.toggle('sel',j===i))}
function openCar(id){const c=cars.find(x=>x.id===id);if(!c)return;const modal=$('#modal');modal.classList.remove('hidden');modal.innerHTML=`<div class="sheet">${photoHTML(c)}<h2>${c.brand} ${c.model}</h2><div class="sub">${c.year} · ${money(c.mileage)} км · ${c.city}</div><div class="meta"><div><small>Цена</small><b>${money(c.price)} ₽</b></div><div><small>Владельцы</small><b>${c.owners}</b></div><div><small>Регистрация</small><b>${c.registered}</b></div><div><small>Двигатель</small><b>${c.engine}</b></div><div><small>Цвет</small><b>${c.color}</b></div><div><small>Дата</small><b>${c.listedDays} дн. назад</b></div></div><div class="box"><small>ОПИСАНИЕ</small>${c.desc}</div><div class="box"><small>ПРИЧИНА ПРОДАЖИ</small>${c.reason}</div><div class="box"><small>ПРОДАВЕЦ</small>${c.seller} · ${c.sellerStyle}</div><div class="chips"><span class="chip">${c.views} просмотров</span><span class="chip">${c.favs} в избранном</span></div><div class="box competitors"><small>ПОХОЖИЕ ОБЪЯВЛЕНИЯ</small><div class="competitorRow"><span>${c.brand} ${c.model}</span><b>${money(Math.round(c.price*0.96/1000)*1000)} ₽</b></div><div class="competitorRow"><span>${c.brand} ${c.model}</span><b>${money(Math.round(c.price*1.04/1000)*1000)} ₽</b></div><div class="competitorRow"><span>${c.brand} ${c.model}</span><b>${money(Math.round(c.price*1.09/1000)*1000)} ₽</b></div></div><div class="chat" id="chat"><b>${c.seller}</b>: «Здравствуйте. Да, машина пока продаётся.»</div><div class="chatInput"><input id="msg" placeholder="Написать продавцу..."><button class="smallBtn" onclick="sendMsg(${id})">Отправить</button></div><div class="actions"><button class="buy secondary" onclick="inspectCar(${id})">Осмотреть</button><button class="buy secondary" onclick="testDrive(${id})">Тест-драйв</button></div><div class="actions"><button class="buy secondary" onclick="buyReport(${id})">Автотека · 150 ₽</button><button class="buy secondary" onclick="vinCheck(${id})">VIN · 250 ₽</button></div><div class="actions"><button class="buy" onclick="buy(${id},${c.price})">Купить</button><button class="buy secondary" onclick="closeModal()">Закрыть</button></div></div>`;fetchWikiPhotos(c.brand,c.model).then(urls=>{c.photoSet=urls;c.photo=urls[0];const m=$('#detailMainPhoto');if(m&&urls[0])m.src=urls[0];const t=document.querySelector('.thumbs');if(t&&urls.length>1)t.innerHTML=urls.map((u,i)=>`<button class="thumb ${i===0?'sel':''}" onclick="pickDetailPhoto(${i},${c.id})"><img src="${u}"></button>`).join('')});}
function sellerReply(c,text){const t=text.toLowerCase();if(/курил|сигар|дым/.test(t))return c.conditionSeed%3===0?'В салоне не курили, запаха табака нет.':'Курили раньше, но салон чистили. Лучше проверить самому.';if(/салон|сидень|кожа|обив/.test(t))return c.conditionSeed%2?'Салон обычный для такого пробега, есть небольшие следы эксплуатации.':'Салон в нормальном состоянии, сильных повреждений нет.';if(/бит|дтп|авар|крашен|красил/.test(t))return c.inspectSeed%3===0?'По кузову красилось левое переднее крыло, остальное надо смотреть на месте.':'Серьёзных ДТП не припомню, мелкие косметические работы могли быть.';if(/двиг|мотор|масл|дым/.test(t))return c.conditionSeed%2?'Мотор работает ровно, масло между заменами сильно не доливаю.':'По двигателю вопросов не замечал, но диагностику лучше сделать.';if(/короб|акпп|мкпп|сцеп/.test(t))return c.conditionSeed%3===0?'Коробка переключает с небольшим толчком на холодную.':'По коробке всё нормально, во всяком случае я проблем не замечал.';if(/цена|дорог|скид|торг|отдад/.test(t)){const min=Math.round(c.price*(c.urgent?.92:.95)/1000)*1000;return c.sellerStyle==='торгующийся'?`У капота готов немного уступить. Ниже ${money(min)} ₽ не хотел бы.`:`Цена выставлена с запасом на небольшой торг. Серьёзно снижать пока не готов.`;}if(/обслуж|то|масло|ремонт/.test(t))return c.conditionSeed%2?'Последнее обслуживание делал недавно, чеки частично сохранились.':'Обслуживал по мере необходимости, полный список работ не веду.';if(/перв|владел|сколько/.test(t))return `По документам владельцев ${c.owners}. Машина оформлена в ${c.registered} году.`;if(/комплект|резин|колес|диск/.test(t))return c.conditionSeed%2?'Есть комплект зимних колёс, состояние обычное.':'Сейчас стоит комплект, который виден на фото; второй комплект не обещаю.';if(/почему прода|прода[её]/.test(t))return c.reason+'.';return ['Могу рассказать подробнее, что именно интересует?','По этой машине лучше отвечу конкретно на вопрос, чтобы ничего не перепутать.','Да, давайте по порядку — машина у меня перед глазами.'][Math.abs(text.length+c.id)%3];}
function sendMsg(id){const c=cars.find(x=>x.id===id),input=$('#msg');if(!input.value.trim())return;const text=input.value.trim();$('#chat').innerHTML+=`<div class="msgMe">Вы: «${text}»</div><div class="msgSeller"><b>${c.seller}</b>: «${sellerReply(c,text)}»</div>`;input.value='';}
function inspectCar(id){const c=cars.find(x=>x.id===id);const findings=[];if(c.conditionSeed%4===0)findings.push('На левом крыле заметна разница оттенка краски.');if(c.conditionSeed%3===0)findings.push('Есть мелкие сколы на капоте и переднем бампере.');if(c.mileage>150000)findings.push('Салон заметно потёрт в местах обычного контакта.');if(c.conditionSeed%5===0)findings.push('Одна из фар имеет следы запотевания.');if(!findings.length)findings.push('При визуальном осмотре серьёзных внешних проблем не обнаружено.');$('.sheet').insertAdjacentHTML('beforeend',`<div class="report"><b>Осмотр автомобиля</b>${findings.map(x=>`<p>• ${x}</p>`).join('')}<p>Визуальный осмотр не заменяет диагностику на СТО.</p></div>`);}
function testDrive(id){const c=cars.find(x=>x.id===id);localStorage.setItem('p_test_done','1');if(c.testDriveSeed<22){$('.sheet').insertAdjacentHTML('beforeend',`<div class="report"><b>${c.seller}</b><p>«Извините, тест-драйв не дам. Можете посмотреть машину на месте.»</p></div>`);return}const findings=[];if(c.conditionSeed%4===0)findings.push('При торможении ощущается лёгкая вибрация.');if(c.conditionSeed%3===0)findings.push('На неровностях слышен небольшой стук спереди.');if(c.conditionSeed%5===0)findings.push('На холодную коробка переключается с небольшим толчком.');if(!findings.length)findings.push('На коротком тест-драйве явных посторонних симптомов не обнаружено.');$('.sheet').insertAdjacentHTML('beforeend',`<div class="report"><b>Тест-драйв</b><p>${c.seller} согласился прокатиться вместе с вами.</p>${findings.map(x=>`<p>• ${x}</p>`).join('')}</div>`);}
function buy(id,p){const c=cars.find(x=>x.id===id);if(!c||bought.has(id)){alert('Этот экземпляр уже недоступен.');return}if(balance<p){alert('Не хватает денег.');return}balance-=p;bought.add(id);garage.push({...c,buyPrice:p,diagnosed:false,ready:false,listed:false,serviceIssues:[],prep:[],historyChecked:false,vinChecked:false,passport:[{year:c.registered,owner:c.owners>1?'Первый владелец':'Первый владелец',event:'Регистрация автомобиля'}],deal:{buy:p,repair:0,prep:0,inspection:0,sale:0}});save();closeModal();render();}
function autodata(c){return {accidents:c.id%4===0?2:c.id%3===0?1:0,damage:c.id%4===0?'Левое крыло и передний бампер':c.id%3===0?'Задний бампер':'ДТП по официальным данным не обнаружены',realMileage:c.id%5===0?c.mileage+38000:c.mileage,twist:c.id%5===0,owners:c.owners,service:c.id%2?'Есть отдельные записи':'История обслуживания частичная'} }
function buyReport(id){const c=cars.find(x=>x.id===id);if(balance<150){alert('Не хватает денег.');return}balance-=150;const r=autodata(c);save();$('.sheet').insertAdjacentHTML('beforeend',`<div class="report"><b>Автотека</b><p>ДТП: ${r.accidents?`обнаружено — ${r.damage}`:'не обнаружено'}</p><p>Реальный пробег: ${money(r.realMileage)} км ${r.twist?'— есть расхождение с объявлением':''}</p><p>Владельцев: ${r.owners}</p><p>Обслуживание: ${r.service}</p></div>`)}
function vinCheck(id){const c=cars.find(x=>x.id===id);if(balance<250){alert('Не хватает денег.');return}balance-=250;save();$('.sheet').insertAdjacentHTML('beforeend',`<div class="report"><b>VIN-проверка</b><p>Идентификатор: ${String(c.brand).slice(0,2).toUpperCase()}-${c.id.toString().padStart(8,'0')}-RU</p><p>Юридических ограничений: ${c.id%7===0?'обнаружены — требуется осторожность':'не обнаружено'}</p><p>Регистрация: ${c.city}</p></div>`)}
function diagnose(i){const c=garage[i];if(c.diagnosed){alert('Эта машина уже проходила диагностику.');return}if(balance<2000){alert('Не хватает денег на СТО.');return}balance-=2000;c.diagnosed=true;c.deal.inspection=2000;c.serviceIssues=makeIssues(c);save();garageView()}
function makeIssues(c){const common=[['Замена масла и фильтра',3200],['Передние тормозные колодки имеют заметный износ',4800],['Втулки стабилизатора требуют внимания',4200],['Масло в АКПП желательно обновить',7800],['Небольшая течь прокладки двигателя',6500],['Регламентная замена свечей',2600],['Проверка/замена тормозной жидкости',2400]];let n=c.mileage>150000?3:c.mileage>100000?2:1;let arr=[];for(let k=0;k<n;k++){let q=common[(c.id+k*2)%common.length];arr.push({name:q[0],cost:q[1]+((c.id+k)%5)*500,done:false})}return arr}
function fixIssue(i,j){const c=garage[i],x=c.serviceIssues[j];if(x.done)return;if(balance<x.cost){alert('Не хватает денег.');return}balance-=x.cost;x.done=true;c.deal.repair+=x.cost;save();garageView()}
function prepare(i){const c=garage[i];if(c.ready){alert('Автомобиль уже подготовлен.');return}if(!c.diagnosed){alert('Сначала диагностика.');return}if(c.serviceIssues.some(x=>!x.done)){alert('Сначала реши, что ремонтировать.');return}c.ready=true;save();garageView()}
function prepChoice(i,type){const c=garage[i];c.prep=c.prep||[];if(c.prep.some(x=>x.type===type)){alert('Эта работа уже выполнена.');return}const costs={polish:6000,clean:7000,wheels:8000,cheapWheels:2500};const labels={polish:'Полировка кузова',clean:'Химчистка салона',wheels:'Восстановление дисков',cheapWheels:'Покраска дисков бюджетным способом'};if(balance<costs[type]){alert('Не хватает денег.');return}balance-=costs[type];c.deal.prep+=costs[type];c.prep.push({type,label:labels[type],quality:type==='cheapWheels'?'бюджетная':'хорошая'});save();garageView()}
function listCar(i){const c=garage[i];if(c.listed){alert('Автомобиль уже выставлен.');return}if(!c.ready){alert('Сначала подготовь автомобиль.');return}c.listed=true;c.listPrice=Math.round(c.buyPrice*1.18/1000)*1000;c.listCity=c.city;c.listViews=0;c.listFavs=0;c.listedAt=Date.now();save();garageView()}
function ownListing(c,i){if(!c.listed)return '';return `<div class="listingState">Выставлена: ${money(c.listPrice)} ₽ · ${c.listViews||0} просмотров · ${c.listFavs||0} в избранном · ${c.listCity}</div>`}
function garageView(){$('#brands').innerHTML='';$('#reset').style.display='none';$('#title').textContent='Мой гараж';$('#count').textContent=`${garage.length} автомобилей`;if(!garage.length){$('#catalog').innerHTML='<div class="empty">Гараж пуст.</div>';return}$('#catalog').innerHTML=garage.map((c,i)=>{const pending=(c.prep||[]).map(x=>x.type);return `<article class="card"><div class="photo"><img src="${c.photo}"><span class="badge">${c.listed?'Выставлена':c.diagnosed?(c.serviceIssues.some(x=>!x.done)?'Есть замечания':'Проверено'):'Не проверено'}</span></div><div class="body"><div class="name">${c.brand} ${c.model}</div><div class="sub">Покупка: ${money(c.buyPrice)} ₽ · ${c.year} · ${money(c.mileage)} км</div><div class="actions"><button class="smallBtn" onclick="diagnose(${i})" ${c.diagnosed?'disabled':''}>${c.diagnosed?'СТО пройдено':'Проверить состояние · 2 000 ₽'}</button><button class="smallBtn" onclick="passportView(${i})">Паспорт</button></div>${c.diagnosed?`<div class="serviceBox"><div class="serviceTitle">Результат СТО</div>${c.serviceIssues.map((x,j)=>`<div class="issue"><div><b>${x.name}</b></div><strong>${money(x.cost)} ₽</strong>${x.done?'<span class="done">Готово</span>':`<button class="smallBtn" onclick="fixIssue(${i},${j})">Устранить</button>`}</div>`).join('')||'<div class="profit">Серьёзных проблем не найдено.</div>'}</div>`:''}${!c.ready?`<div class="prepButtons">${!pending.includes('polish')?`<button class="smallBtn" onclick="prepChoice(${i},'polish')">Полировка · 6 000 ₽</button>`:''}${!pending.includes('clean')?`<button class="smallBtn" onclick="prepChoice(${i},'clean')">Химчистка · 7 000 ₽</button>`:''}${!pending.includes('wheels')?`<button class="smallBtn" onclick="prepChoice(${i},'wheels')">Восстановить диски · 8 000 ₽</button>`:''}${!pending.includes('cheapWheels')?`<button class="smallBtn" onclick="prepChoice(${i},'cheapWheels')">Покрасить диски · 2 500 ₽</button>`:''}</div>`:''}${c.diagnosed&&!c.ready&&!c.serviceIssues.some(x=>!x.done)?`<button class="buy secondary" onclick="prepare(${i})">Подготовить автомобиль</button>`:''}${c.ready&&!c.listed?`<button class="buy" onclick="listCar(${i})">Выставить на продажу</button>`:''}${ownListing(c,i)}${c.listed?`<button class="smallBtn" onclick="dealStats(${i})">Статистика сделки</button>`:''}</div></article>`}).join('');updateTop()}
function passportView(i){const c=garage[i];$('#modal').classList.remove('hidden');$('#modal').innerHTML=`<div class="sheet"><h2>Паспорт автомобиля</h2><p>${c.brand} ${c.model}</p><div class="report"><p>Год: ${c.year}</p><p>Пробег: ${money(c.mileage)} км</p><p>Покупка: ${money(c.buyPrice)} ₽</p><p>Текущий владелец: вы</p><p>История: автомобиль приобретён у ${c.seller} в ${c.city}.</p></div><button class="buy close" onclick="closeModal()">Закрыть</button></div>`}
function dealStats(i){const c=garage[i];const total=c.deal.buy+c.deal.repair+c.deal.prep+c.deal.inspection;const projected=c.listPrice||0;$('#modal').classList.remove('hidden');$('#modal').innerHTML=`<div class="sheet"><h2>Статистика сделки</h2><div class="report"><p>Покупка: ${money(c.deal.buy)} ₽</p><p>СТО: ${money(c.deal.inspection)} ₽</p><p>Ремонт: ${money(c.deal.repair)} ₽</p><p>Подготовка: ${money(c.deal.prep)} ₽</p><p><b>Вложено: ${money(total)} ₽</b></p><p>Цена продажи: ${money(projected)} ₽</p><p><b>Потенциальный результат: ${money(projected-total)} ₽</b></p></div><button class="buy close" onclick="closeModal()">Закрыть</button></div>`}
function favoritesView(){$('#title').textContent='Избранное';$('#count').textContent='';$('#brands').innerHTML='';$('#reset').style.display='none';const ids=Object.keys(favorites).map(Number);const items=ids.map(id=>cars.find(c=>c.id===id)).filter(Boolean);$('#catalog').innerHTML=items.map(c=>bought.has(c.id)?`<article class="card sold"><div class="body"><div class="name">${c.brand} ${c.model}</div><div class="sub">Объявление снято с продажи</div></div></article>`:card(c)).join('')||'<div class="empty">В избранном пока ничего нет.</div>';updateTop()}
const achievementDefs=[['first_buy','Первая покупка','Купить первый автомобиль.'],['first_diag','На СТО','Провести первую диагностику.'],['first_sale','Первая продажа','Выставить автомобиль на продажу.'],['profit100k','Первые 100 000','Получить суммарно 100 000 ₽ прибыли.'],['five_cars','Автопарк','Купить 5 автомобилей.'],['ten_favs','Популярное объявление','Добавить 10 автомобилей в избранное.'],['city_hopper','Путешественник','Посетить другой город.'],['first_test','Тестировщик','Провести первый тест-драйв.']];
function checkAchievements(){const set=(k,v)=>{if(v)achievements[k]=true};set('first_buy',garage.length>=1);set('first_diag',garage.some(x=>x.diagnosed));set('first_sale',garage.some(x=>x.listed)||listings.length>0);set('profit100k',profit>=100000);set('five_cars',garage.length>=5);set('ten_favs',Object.keys(favorites).length>=10);set('first_test',localStorage.getItem('p_test_done')==='1');set('city_hopper',localStorage.getItem('p_city_hopper')==='1');localStorage.setItem('p_achievements',JSON.stringify(achievements));}
function achievementsView(){checkAchievements();$('#brands').innerHTML='';$('#reset').style.display='none';$('#title').textContent='Достижения';$('#count').textContent='';$('#catalog').innerHTML=`<div class="achievementsGrid">${achievementDefs.map(([id,name,desc])=>`<article class="achievement ${achievements[id]?'doneAch':''}"><div class="achIcon">${achievements[id]?'✓':'○'}</div><div><b>${name}</b><p>${desc}</p><span>${achievements[id]?'Выполнено':'Не выполнено'}</span></div></article>`).join('')}</div>`;updateTop()}
function timeView(){$('#modal').classList.remove('hidden');$('#modal').innerHTML=`<div class="sheet"><h2>Время</h2><p>День ${day}, ${String(gameHour).padStart(2,'0')}:00</p><p>Текущий город: <b>${currentCity}</b></p><p>Доступно сна сегодня: ${sleepLeft} ч.</p><div class="timeBtns">${[1,3,6,12].map(h=>`<button class="buy ${h>sleepLeft?'disabled':''}" onclick="sleep(${h})">Поспать ${h} ч.</button>`).join('')}</div><div class="travelBox"><b>Поездка в другой город</b><p class="sub">Стоимость и время зависят от расстояния.</p><select id="travelCity" class="formGrid" style="width:100%;background:#0f141a;border:1px solid #303744;color:#fff;border-radius:10px;padding:11px;margin-top:8px">${cities.filter(x=>x!==currentCity).map(x=>`<option>${x}</option>`).join('')}</select><button class="buy secondary" onclick="travelTo($('#travelCity').value)">Поехать</button></div><p class="sub">Полные игровые сутки проходят примерно за 6 минут реального времени.</p><button class="buy close" onclick="closeModal()">Закрыть</button></div>`}
function travelTo(city){if(!city||city===currentCity)return;const a=cities.indexOf(currentCity),b=cities.indexOf(city),dist=Math.abs(a-b)+1;const cost=dist*2500;const hours=Math.min(5,Math.max(1,Math.ceil(dist/2)));if(balance<cost){alert(`На поездку нужно ${money(cost)} ₽.`);return}if(hours>sleepLeft){alert('На сегодня не хватает доступного времени для поездки.');return}balance-=cost;sleepLeft-=hours;currentCity=city;localStorage.setItem('p_city_hopper','1');advanceTime(hours);save();closeModal();render()}
function sleep(h){if(h>sleepLeft){alert('На сегодня лимит сна исчерпан.');return}sleepLeft-=h;advanceTime(h);save();closeModal();render();}
function advanceTime(h){gameHour+=h;while(gameHour>=24){gameHour-=24;day++;sleepLeft=12;marketTick();}}
function marketTick(){cars.forEach(c=>{if(Math.random()<.08)c.price=Math.round(c.price*(.97+Math.random()*.05)/1000)*1000;if(Math.random()<.05)c.listedDays+=1;if(Math.random()<.05)c.views+=1;if(Math.random()<.03)c.favs+=1});listings.forEach(x=>{if(x.active&&Math.random()<.18)x.listViews=(x.listViews||0)+1;if(x.active&&Math.random()<.08)x.listFavs=(x.listFavs||0)+1});garage.forEach(c=>{if(c.listed){c.listViews=(c.listViews||0)+Math.floor(Math.random()*4);c.listFavs=(c.listFavs||0)+(Math.random()<.18?1:0);}});}
let realTick=0;setInterval(()=>{gameHour+=1;realTick++;if(gameHour>=24){gameHour=0;day++;sleepLeft=12;marketTick()}save();if(!document.querySelector('#modal:not(.hidden)')){const active=document.querySelector('.nav.active');if(active&&active.id==='marketTab')render();else if(active&&active.id==='garageTab')garageView();}},15000);
function showMarket(){$('#marketTab').classList.add('active');$('#garageTab').classList.remove('active');$('#favTab').classList.remove('active');$('#achTab').classList.remove('active');$('#filterBtn').style.display='inline-block';$('#reset').style.display='block';render()}
function showGarage(){$('#marketTab').classList.remove('active');$('#garageTab').classList.add('active');$('#favTab').classList.remove('active');$('#achTab').classList.remove('active');$('#filterBtn').style.display='none';$('#reset').style.display='none';garageView()}
function showFav(){$('#marketTab').classList.remove('active');$('#garageTab').classList.remove('active');$('#favTab').classList.add('active');$('#achTab').classList.remove('active');$('#filterBtn').style.display='none';$('#reset').style.display='none';favoritesView()}
function showAchievements(){$('#marketTab').classList.remove('active');$('#garageTab').classList.remove('active');$('#favTab').classList.remove('active');$('#achTab').classList.add('active');$('#filterBtn').style.display='none';$('#reset').style.display='none';achievementsView()}
function closeModal(){$('#modal').classList.add('hidden')}
$('#marketTab').onclick=showMarket;$('#garageTab').onclick=showGarage;$('#favTab').onclick=showFav;$('#achTab').onclick=showAchievements;$('#filterBtn').onclick=openFilters;$('#timeBtn').onclick=timeView;$('#reset').onclick=()=>{Object.assign(filters,{brand:'Все',city:'Все',minPrice:'',maxPrice:'',minYear:'',maxMileage:'',sort:'new'});render()};checkAchievements();updateTop();render();primePhotoBase();
